### ISSUE TITLE
Weights + input mask ?

### ISSUE THREAD

**Issue by ikramabdel** [DIAGNijmegen/pathology-hooknet-tls#1]
Great work ! thank you so much for sharing. 
I was wondering if you plan to make the weights of your model public so we can test the inference code ? 
and also if you can share how to obtain the input mask (the tumor segmentation algorithm is no longer available) so we can also test on another dataset.

**Comment by martvanrijthoven** [comment]
Dear AbdelIka,

Thank you for your interest in our work!

You can download the weights of the model here: https://zenodo.org/records/10614942

For input masks, a tissue-versus-background masks needs to be created. For new datasets you can use https://grand-challenge.org/algorithms/tissue-background-segmenation/. This should still be available, but please let me know if you have any problems with it and we can contact the creator.

Best wishes,
Mart

**Comment by ikramabdel** [comment]
Thank you ! 

Yes i have requested access on  [Tissue background segmentation ](https://grand-challenge.org/algorithms/tissue-background-segmenation/) and awaiting on a response. 

But to clarify both inputs should be pyramidal images ?

**Comment by martvanrijthoven** [comment]
Yes you are correct both should be pyramidal.

Best wishes,
Mart
