### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by fbenedett** [DIAGNijmegen/pathology-hooknet-tls#11]
Hello,

I was trying to install the library but I get this error:

`sudo docker build -t hooknet-tls .
[+] Building 0.1s (2/2) FINISHED                                                         docker:default
 => [internal] load build definition from Dockerfile                                               0.0s
 => => transferring dockerfile: 2B                                                                 0.0s
 => [internal] load .dockerignore                                                                  0.0s
 => => transferring context: 2B                                                                    0.0s
WARNING: buildx: failed to read current commit information with git rev-parse --is-inside-work-tree
ERROR: failed to solve: failed to read dockerfile: open /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount510105782/Dockerfile: no such file or directory
`
My docker version is:
`docker -v
Docker version 24.0.5, build ced0996
`

What am I doing wrong?
I am on Ubuntu 22.04

**Comment by martvanrijthoven** [comment]
Dear Fabrizio Benedetti,

I have not encountered this problem myself.
From where are you building the Dockerfile and are you able to build other Dockerfiles?

**Comment by fbenedett** [comment]
I am in the hooknet-tls directory.  The one I got with "git clone".
Look:
`ls
Dockerfile  DockerfileDIAG  docs  hooknettls  LICENSE  paper  README.md  setup.py  tests  weights.h5
`

**Comment by martvanrijthoven** [comment]
Yes I am also not sure what is going on here. 

Maybe you can try to check permissions of the Dockerfile
and you could try to explicit set the Dockerfile by adding "-f Dockerfile "

**Comment by fbenedett** [comment]
I found the problem.
I do not know why, but on Ubuntu the snap installation of docker does not work.
In ubuntu, one has to install the apt version of docker with:
`sudo apt install docker.io`
